{% set version = "1.17.0" %}

package:
  name: six
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/s/six/six-{{ version }}.tar.gz
  sha256: ff70335d468e7eb6ec65b95b99d3a2836546063f63acc5171de367e834932a81

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - six
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://six.readthedocs.io/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python 2 and 3 compatibility utilities
  description: |
    Six provides simple utilities for wrapping over differences between
    Python 2 and Python 3. It is intended to support codebases that work on
    both Python 2 and 3 without modification. six consists of only one Python
    file, so it is painless to copy into a project.
  doc_url: https://six.readthedocs.io/
  dev_url: https://github.com/benjaminp/six

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - ocefpaf
