{% set name = "six" %}
{% set version = "1.11.0" %}
{% set sha256 = "70e8a77beed4562e7f14fe23a786b54f6296e34344c23bc42f07b15018ff98e9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 2
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - six

about:
  home: http://pypi.python.org/pypi/six/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python 2 and 3 compatibility utilities
  description: |
    Six provides simple utilities for wrapping over differences between
    Python 2 and Python 3. It is intended to support codebases that work on
    both Python 2 and 3 without modification. six consists of only one Python
    file, so it is painless to copy into a project.
  doc_url: http://pythonhosted.org/six/
  dev_url: https://github.com/benjaminp/six

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - ocefpaf
